### PR TITLE
Farm Multiple Pokestops while walking paused / tweak miss rate

### PR DESCRIPTION
**Pull request by MTK4355**

### CODE REVIEW

**Comment by MTK4355** [comment]
Any ideas on what is happening with the farming issue? I cannot replicate the problem. Seems to be pretty widespread though. 

MK

**Comment by Ar1i** [comment]
uhm could you fix the conflicts? :s

**Comment by Ar1i** [comment]
If not, i will do it later. But atm i am not at home!

**Comment by MTK4355** [comment]
Weird.. Those didn't show up when I pushed to my Git from VS and I thought I was in sync.

**Pull request closed without merging**
