### PR TITLE
Look for pokemon's nearby while walking to destination, Sorted lists of Pokemons and temp fix to be able to compile.

### PR DESCRIPTION
**Pull request by baeckstrom**
This commit enables searching for pokemon's while walking between locations.

### CODE REVIEW

**Comment by baeckstrom** [comment]
Also added sorted lists for pokemons to easier find them.

**Comment by StephenSocksTv** [comment]
How do I go into change this. I tried but it wasn't working with visual studio

**Comment by stormlolz** [comment]
@baeckstrom you have try this?
You catch more more more pokemon?

**Comment by baeckstrom** [comment]
@stormlolz I have been using this for a while now, without this change the bot will only catch pokemon's that are located around pokestops. If you travel a long distance those pokemon's that are located along the way won't be catched.

**Comment by baeckstrom** [comment]
@StephenSocksTv This need's to be merged, or you should be able to cherrypick my changes by adding my repo as an additional remote and fetch it from there.

**Comment by Ar1i** [comment]
Good job, i removed it yesterday so i dont send to much requests. Will merge that later!

**Comment by Ar1i** [comment]
Accepting that if i am back home.

**Comment by baeckstrom** [comment]
Another fix as i got annoyed by the location selector that sent me back to Central Park all the time, now uses the previous location instead.

**Pull request merged**
