### PR TITLE
Add an option for the berry

### PR DESCRIPTION
**Pull request by ymicky**
I have added an option in the GUI for enable or disable the using of the berry.

### CODE REVIEW

**Comment by globsch** [comment]
but why should we do that?

**Comment by ymicky** [comment]
If you want to use a sniperbot berrys are very useful for catching rare pokemon and this bot works also great without using berrys. I think berrys are more useful for catching rare pokemon instead of cp 400 taubsis...

**Comment by ArrobaKappa** [comment]
I believe that one control the probability would be perfect.

**Comment by ymicky** [comment]
Or maybe a CP minimum

**Comment by galinha1** [comment]
i have look de API and, and i think  its possible to do this, and this as like the ""iv transferer" have one command ""or"" or ""and"".

**Pull request merged**
