### PR TITLE
Better incubation handling

### PR DESCRIPTION
**Pull request by setoy**
Final request still missing, but fixes a few bugs

### CODE REVIEW

**Comment by ezkoria** [comment]
Now i have a new problem  ( " ### WE CANT FIND ANY POKESTOPS IN A RANGUE OF XXXXXM!" " WE CANT FIND ANY POKESTOPS, WHICH ARE UNUSED ! PROBABLY SERVER UNSTABLE, OR VISITED THEM ALL. RETRYING.. ###" )

**Comment by setoy** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1202

**Comment by ezkoria** [comment]
WOPS, I apologize for comment on where he should thank you very much for the answer.

**Comment by canbabacan** [comment]
https://map.goradar.io/ there are still running some maps. I remember this bot was use to pokevision before. So why dont you use that map for bot?

**Pull request merged**
