### PR TITLE
Dutch Translation

### PR DESCRIPTION
**Pull request by AboveColin**

### CODE REVIEW

**Comment by Sander523i** [comment]
I can do the Dutch translation.

**Comment by Sander523i** [comment]
only one problem there is no Dutch version of the game that means that items like lucky egg or incense won't be translated unless you prefer that I do translate them but I won't translate pokémon names

**Comment by AboveColin** [comment]
i've already made a dutch translation... 😅😅

**Comment by BigManTyrone** [comment]
was already made #1040

**Comment by Sander523i** [comment]
oké np 

found that out after making my translation

**Comment by nietmarvin** [comment]
dude, heb ik net een vertaling afgerond, heb jij al 1 gemaakt lol

Dude, just have been making a dutch translation only to see you already made one lol

**Pull request closed without merging**
