### PR TITLE
Remake of Telegram /information command

### PR DESCRIPTION
**Pull request by DeltaCore**
Modified the /information command.
``/information <topic>``

Topics:
Levelup
Catch
Evolve
Transfer
Pokestop

These are the topics about what you are getting notified about.
Basicly you get a telegram message with almost the same line as in the console.

Using translations for that.

New message id's:

These are the notification descriptions (which are used when you enter ``/information`` alone)
on the upper and the id's on the lower half.
``` c#
private Dictionary<TelegramUtilInformationTopics, String> _informationDescriptionDefault = new Dictionary<TelegramUtilInformationTopics, String>() {
	{ TelegramUtilInformationTopics.Pokestop, @"Notifies you when a pokestop was visited" },
	{ TelegramUtilInformationTopics.Catch, @"Notifies you when a pokemon is caught" },
	{ TelegramUtilInformationTopics.Evolve, @"Notifies you when a pokemon was evolved" },
	{ TelegramUtilInformationTopics.Transfer, @"Notifies you when a pokemon is transfered" },
	{ TelegramUtilInformationTopics.Levelup, @"Notifies you when you got a level up" },
};
private Dictionary<TelegramUtilInformationTopics, String> _informationDescriptionIDs = new Dictionary<TelegramUtilInformationTopics, String>() {
	{ TelegramUtilInformationTopics.Pokestop, @"telegram_pokestop_description" },
	{ TelegramUtilInformationTopics.Catch, @"telegram_catch_description" },
	{ TelegramUtilInformationTopics.Evolve, @"telegram_evolve_description" },
	{ TelegramUtilInformationTopics.Transfer, @"telegram_transfer_description" },
	{ TelegramUtilInformationTopics.Levelup, @"telegram_levelup_description" },
};
```

These are the notification messages on the upper and the id's on the lower half.
``` c#
public Dictionary<TelegramUtilInformationTopics, String> _informationTopicDefaultTexts = new Dictionary<TelegramUtilInformationTopics, String>() {
	{ TelegramUtilInformationTopics.Pokestop, "Visited a pokestop {0}\nXP: {1}, Eggs: {2}, Gems:{3}, Items: {4}" },
	{ TelegramUtilInformationTopics.Catch, "Caught {0} CP {1} IV {2}% using {3} got {4} XP." },
	{ TelegramUtilInformationTopics.Evolve, "Evolved {0} CP {1} {2}%  to {3} CP: {4} for {5}xp" },
	{ TelegramUtilInformationTopics.Transfer, "Transfer {0} CP {1} IV {2}% (Best: {4} CP)" },
	{ TelegramUtilInformationTopics.Levelup, "You ({0}) got Level Up! Your new Level is now {1}!" },
};

public Dictionary<TelegramUtilInformationTopics, String> _informationTopicDefaultTextIDs = new Dictionary<TelegramUtilInformationTopics, String>() {
	{ TelegramUtilInformationTopics.Pokestop, @"telegram_pokestop" },
	{ TelegramUtilInformationTopics.Catch, @"telegram_catch" },
	{ TelegramUtilInformationTopics.Evolve, @"telegram_evolve" },
	{ TelegramUtilInformationTopics.Transfer, @"telegram_transfer" },
	{ TelegramUtilInformationTopics.Levelup, @"telegram_levelup" },
};
```
Found in TelegramUtils.cs:48

If there are any questions, email me marcel(at)ccmob.net

### CODE REVIEW

**Comment by monoxacc** [comment]
Nice work.
Can u add a selective information like following command: /information catch levelup
Will inform about catch & levelup only.
Cann u add this?

**Comment by DeltaCore** [comment]
Yes. It is like that implemented. You enable / disable the topic.
Means:
/informatio catch for the first time enables it, and the second time disables it.

So you can toggle the topics on and off you want and only these ones you need.

And thanks for pointing out that i can observe these. I will have a look into it when i have time. But for now it should work +1:

**Comment by monoxacc** [comment]
TelegramUtil.getInstance() returns NULL if telegram isn't in use

**Comment by DeltaCore** [comment]
How was it fixed if i may ask ?

**Comment by monoxacc** [comment]
in dirty way: try catches^^
here: https://github.com/Ar1i/PokemonGo-Bot/commit/d4ed1e32b879116b0c5210e3e477c453a1940fcf
& here: https://github.com/Ar1i/PokemonGo-Bot/commit/d9e80c73aad6c792e7138e979366b51bd6479f3b

**Pull request merged**
