### PR TITLE
Czech translation request

### PR DESCRIPTION
**Pull request by ElektronikCZ**
Hello sir, or lady, whatever gender you are.

I made this translation into Czech language and id be honored if you could put it in your bot, i can provide a flag too if needed.

Thanks

### CODE REVIEW

**Comment by Ar1i** [comment]
flag would be nice tho

**Comment by Croc0008** [comment]
Line 42 is German and noch Czech, isn't it?
Or I am only stupid.

**Comment by ElektronikCZ** [comment]
Oh sorry, my bad, it should be fixed now.
And here is the flag
czech-republic-flag-icon

**Comment by Methno** [comment]
HI - As First Big Thanks - i would like to help with Translations - Polish/Greek/ukrainian  -started with polish Translations - Will attach file later

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by SscSPs** [comment]
Why is it still not merged? 
Not that I WANT it, just wondering.

**Pull request closed without merging**
