### PR TITLE
Update it to compile with .NET Framework 4.5.2 instead of 4.5

### PR DESCRIPTION
**Pull request by SscSPs**
Just set up my Visual studio to work properly with thiss and it said it wouldn't load the project untill it is complied with .NET 4.5.2

### CODE REVIEW

**Comment by Logxn** [comment]
uhm nah

**Comment by SscSPs** [comment]
what?
would this make something incompatible?

**Comment by Logxn** [comment]
naaah you must have misunderstood the error from VS

**Comment by SscSPs** [comment]
Well, this is what i got:
load problem

And when i try to download and install 4.5, it says it is already a part of the OS and don't needs installation(or something like that) and do not proceeds.

**Comment by Ar1i** [comment]
Makes no sense, its because you don't own the version

**Comment by SscSPs** [comment]
Okay, well then, can you please tell me how to get 4.5?
And can you please tell me what, or if any, compatibility issues this would
create?
And if it would not, which is my guess, because the base is still 4.0,
please merge this because i might not be able to do much work on this.

**Comment by MTK4355** [comment]
http://stackoverflow.com/questions/17606178/the-c-sharp-project-is-targeting-net-framework-version-v4-5-which-is-not-in

**Comment by MTK4355** [comment]
Not the only one who has had this issue. Looks like your fix should be to un-install and re-install visual studio.

**Comment by MTK4355** [comment]
Changing the targeting framework can have a serious ripple effect, even when no obvious conflicts arise at first. 

This is especially true when dealing with reflection and de-compiling packaged dlls. 

Even going from 4.5 to 4.5.2 can cause headaches, and that sort of change should only be made when there is a compelling architectural reason to do so.

**Pull request closed without merging**
