### PR TITLE
IV and CP Check moved to TransferDuplicatePokemon and improved

### PR DESCRIPTION
**Pull request by globsch**
- we won't transfer anything with the wrong CV or IV any more, both checked at the same place now
- the amountToSkip is included with the amount of IV's and CP's over the set values
- amountToSkip can now be set to 0!

### CODE REVIEW

**Comment by globsch** [comment]
hmm closed source again? :-(

**Comment by Ar1i** [comment]
yeah, but implementing it! :)

**Comment by crazyandy3** [comment]
ar1i  cen you fix  player status report  i fell in love with the old  bot you had it  orginizd :(

**Comment by Ar1i** [comment]
implemented thanks!

**Comment by crazyandy3** [comment]
my english suck :P  implemented means you olready are tryng to fix it :D??

**Pull request closed without merging**
