### PR TITLE
Add Multi-Stop User Routing and Use Items from GUI controls

### PR DESCRIPTION
**Pull request by MTK4355**
To create a Route:
1. Pause Walking
2. Click the pokestops to include in your route (in the order you want to walk them)
3. Optionally check the Repeat Route box if you want to walk in a loop (not thoroughly tested BEWARE lol)
4. Resume Walking
5. BE PATIENT!! If your bot has already paused at the next pokestop he will start walking again soon. 

If you pause walking again, the route will be cleared and you can create a new route but again, not thoroughly tested so I'm unsure of what will happen if you have an existing unfinished route...

Using the GUI Items controls:
1. Click the button 
2. BE PATIENT the item will be used shortly when the logic circles around to catch up. 

NOTE: "Use Lure" can only be activated if you have first paused walking.

Please Report bugs by creating an issue here, with steps to reproduce and screenshots of the error (in English if possible)

All questions about use should be directed to the Discord General Discussion thread.

### CODE REVIEW

**Comment by k0ut4li4n0s** [comment]
@MTK4355 there isnt any repeat route box

**Comment by MTK4355** [comment]
No? It was under the Pause Walking button. I think that is broken right now anyway.. :)>

**Comment by k0ut4li4n0s** [comment]
There s a transfer button and an IV to Nick button(what this one do :P )

**Comment by k0ut4li4n0s** [comment]
althought it follows the route it gives this "error" message (At least for the 1st time i run it )

**Comment by MTK4355** [comment]
It's the damn commas screwing with Google Directions API. Working on it.

**Comment by k0ut4li4n0s** [comment]
hehe some commas screwing the thang xD. (Is there a tutorial to somehow start programming  ? i am intersted in programming but i dont know  how to start where and with what ,sorry for the offtopic, send me an email if you know sth,thnx)

**Comment by k0ut4li4n0s** [comment]
This happens when have the repeat route box,pockemon dont show too . Good work though on routing ! Much appreciated ! !

**Pull request merged**
