### PR TITLE
Google Routing! (beta though, so keep an eye on it)

### PR DESCRIPTION
**Pull request by MTK4355**

### CODE REVIEW

**Comment by MTK4355** [comment]
Not perfect, but it makes my heart happy.
image
image

**Comment by Viper2k4** [comment]
So i let it run atm. It works. But it seems like it work only somtimes. Because for my town it mostly runs throw the grass like before and use the direct way to a pokestop.

**Comment by Logxn** [comment]
Thats some sweet stuff:) you do good work

**Comment by eengg** [comment]
awesome

**Comment by ntatoo** [comment]
keep up the good work mate
i will try the code that you devlop
@MTK4355

**Pull request merged**
