### PR TITLE
+ Added .txt LOG!!

### PR DESCRIPTION
**Pull request by CP02A**
IMPORTANT:
Please check my work VERY Carefully because I never coded in C# before...
I hope I did it right

(I also made this so People want this feature so you can report errors more easily...)

Please Feel to make a per-Session Log ;)
Oh and the Player Status doesn't log yet, don't have enough time though...

### CODE REVIEW

**Comment by CP02A** [comment]
By the way, my first pull request ;o

**Comment by gise88** [comment]
Great pr! Will probably be better if we can choose to log on file or not.. 
However the following is bad coding style :grin:
```
if (!File.Exists(log))
{
	File.Create(log);
	TextWriter tw = new StreamWriter(log);
	tw.WriteLine(message);
	tw.Close();
}
else if (File.Exists(log))
{
	TextWriter tw = new StreamWriter(log);
	tw.WriteLine(message);
	tw.Close(); 
}
```

Is better to create a function that test if the file does not exist and, if so, create it, then open the stream and write as following:

```
public static void AddLog(string line) {
	if (!File.Exists(log))
		File.Create(log);
	// here you know that the file exists
	TextWriter tw = new StreamWriter(log);
	tw.WriteLine(line);
	tw.Close(); 
}
```

The code is easier to read and there is no replicated code. Try to fix your code! 
https://github.com/CP02A/PokemonGo-Bot/blob/08d36a2afa28b40a25262493e44b96c9a5d1237c/PokemonGo.RocketAPI/Logger.cs#L36
https://github.com/CP02A/PokemonGo-Bot/blob/08d36a2afa28b40a25262493e44b96c9a5d1237c/PokemonGo.RocketAPI/Logger.cs#L57
https://github.com/CP02A/PokemonGo-Bot/blob/08d36a2afa28b40a25262493e44b96c9a5d1237c/PokemonGo.RocketAPI/Logger.cs#L78
https://github.com/CP02A/PokemonGo-Bot/blob/08d36a2afa28b40a25262493e44b96c9a5d1237c/PokemonGo.RocketAPI/Logger.cs#L99

**Comment by CP02A** [comment]
should I close this Pull Request?
@gise88

**Comment by gise88** [comment]
nono, just commit & push the fixed code.. =)

**Comment by CP02A** [comment]
ok thanks, I will tomorrow

**Comment by Ar1i** [comment]
nice work, thanks!

**Pull request merged**
