### PR TITLE
Traditional Chinese(Taiwan) Translation

### PR DESCRIPTION
**Pull request by TCCinTaiwan**
add taiwan.json

### CODE REVIEW

**Comment by TheOk98** [comment]
I'm very new to this website and don't really understand how these pull request works, but I want to contribute to this bot with a swedish translation. Someone help me and tell me how, maybe someone can send me the files that needs to be translated?

**Comment by TheOk98** [comment]
I'm very new to this website and don't really understand how these pull requests works, but I want to contribute to this bot with a swedish translation. Someone help me and tell me how, maybe someone can send me the files that needs to be translated?

**Comment by TCCinTaiwan** [comment]
In fact, I don't know either.
Maybe You should  reference "Merged" pull requests like #2442 .

**Comment by TheOk98** [comment]
Can you PM people on this website?

**Comment by TCCinTaiwan** [comment]
I don't think so.
But you can try to use E-mail. If someone who you want to PM didn't hide mail info in profile.

**Comment by TCCinTaiwan** [comment]
Almost like #2966.
If merge any one of us, another can be closed.

**Pull request closed without merging**
