### PR TITLE
add marker for pokestops

### PR DESCRIPTION
**Pull request by acesyde**
Add blue markers for pokestops on map

### CODE REVIEW

**Comment by Tobiasgenscher** [comment]
thx
nice work , THX !

**Comment by lithatog** [comment]
if visited (not ready) pokestop show in purple markers it would even better

**Comment by czokalapik** [comment]
Thats great! Would be even better to make it like PokeFarmer - every pokestop in set range + Gyms + Closest Pokemons.

I can create Pokestops/Gyms Icons if you'd like

**Comment by Ar1i** [comment]
Could you fix the conflicts? :) would love to put it in!

**Comment by acesyde** [comment]
image

**Comment by Justux204** [comment]
force move on map too

**Pull request closed without merging**
