### PR TITLE
Added incubation request

### PR DESCRIPTION
**Pull request by setoy**
NOT TESTED, CANNOT CURRENTLY CONFIRM OR DENY WORKING!
Thanks to @Lasertrap00

**Edit: Confirmed working now.**

### CODE REVIEW

**Comment by Ar1i** [comment]
nice!

**Comment by Filip1232334** [comment]
Still dont work same problem with poestops why cant it find pokestops in radius 5km

**Comment by setoy** [comment]
#1202

**Comment by stripbash** [comment]
Any Idea by what time it'll be out and working again?

**Comment by bunnymuny** [comment]
12/36h aprox #1274

**Comment by DevilBlyat** [comment]
I would like to make french translation. How can I do that ?

**Comment by Melancolie** [comment]
I was wondering when will there be such an option (of incubation). Will there be settings in the GUI?

**Comment by setoy** [comment]
There already is such a setting in the latest version.

**Comment by DubbinDanny** [comment]
This going to be fixed soon or is there already a fix? :)

**Comment by stripbash** [comment]
@setoy so how do we hatch eggs now, exactly? if you could explain please in a simple language for all the noobs out here?

**Comment by setoy** [comment]
@stripbash Select "Auto incubate" in the GUI?! wtf...

**Comment by stripbash** [comment]
Okay I am not using bot right now because I just got to know about it recently and when I started usingit it wasn't really working

**Comment by DubbinDanny** [comment]
Wait so is the bot actually working/fixed?

**Comment by stripbash** [comment]
No Not yet

**Comment by DubbinDanny** [comment]
Soon to be fixed I assume?

**Comment by stripbash** [comment]
Owner said by today or tomorrow

**Comment by DubbinDanny** [comment]
okay sweet :)

**Pull request merged**
