### PR TITLE
Added Theme to the base Form

### PR DESCRIPTION
**Pull request by LordBunny**
Added a Theme to the base Form (Gui) and it's not done yet, but it will look like this

### CODE REVIEW

**Comment by Xelwon** [comment]
Please, try to clean more your changes.
For example, git files and empty fuctions.
It seems that there are too many unneeded changes.
https://github.com/Ar1i/PokemonGo-Bot/pull/4207/files

**Comment by LordBunny** [comment]
I will update it, Thanks

**Comment by Xelwon** [comment]
ok, thanks, 
you have to delete  
/.gitattributes 
/.gitignore 

and

       private void tabMisc_Click(object sender, EventArgs e)
        {

        }

And after of that.  make in "sycn" button from github client.

**Comment by Xelwon** [comment]
Changing to MetroFramework is not trivial to do for now.

**Pull request closed without merging**
