### PR TITLE
Added encryption to encrypt your password in config file.

### PR DESCRIPTION
**Pull request by Xelwon**
A patch to do it a little more secure.

### CODE REVIEW

**Comment by Ar1i** [comment]
That's not really a encryption, cause you can easily get the plaintext :p Cause it`s even open source, so this won't help anything..

**Comment by Xelwon** [comment]
Yes :D, the Idea was for this. :D. Using the same PC with same user in house and your bro or granpa, cannnot open the config and see the password directly :D.

With this is a little more complex. You must know first the compressión method, aftert the pharafrase and finally search a program to decript it :D.

**Comment by Logxn** [comment]
if you put the crypt function in the textbox_textchanged field you cant get it plaintext anymore.
(Not from official releases)

**Comment by Xelwon** [comment]
You undertood wrong, 

Only encrpyt password value at save in the config.txt file, all other values are decripted (as berore)
Only decript password atl load  form file config.

It is totaly transparent for end user and  rest of programmers.

Only implic that you can reenter the passord first time if you goes from earlier versions.

**Comment by Xelwon** [comment]
I'm redoing it.

**Pull request closed without merging**
