### PR TITLE
[!!] General Beautifier + Pokemon List Sort Buttons (Main GUI) + #1338

### PR DESCRIPTION
**Pull request by IceQ1337**
++ German Translation Misspelling Fix

### CODE REVIEW

**Comment by BigManTyrone** [comment]
love what your doing ice keep it up

**Comment by FrancYescO** [comment]
too much lines for players stats.

**Comment by IceQ1337** [comment]
@FrancYescO There are so many people who dislike the current layout and want the old one back, so i decided to revert it. There are not too much lines, because it's just a status messages which is displayed once in a while... It's much easier to read and if the community wants it, they get it.

**Comment by FrancYescO** [comment]
Yep the new layout was not that good, but these line are here for logging purpose, to see the actual status you have all of infos in the title of the windows... At lest "once in a while" was probably too much now, these "verbose" stats cause to lose lot of history of what happened scrolling up the console

**Comment by IceQ1337** [comment]
Got it. When I'm back home i will try something which might improves the statslog overall.

**Pull request closed without merging**
