### PR TITLE
Remove redundant usings, Code Format, .lib in build to Library/ folder.

### PR DESCRIPTION
**Pull request by BerkanYildiz**

### CODE REVIEW

**Comment by BerkanYildiz** [comment]
Mmh..
You accepted other pull request so my request have conflicts again.. :(

**Comment by Ar1i** [comment]
Yeah.. :( Will fix the conflicts myself later..

**Comment by uaeb** [comment]
Why did you change this to have a virus in it :-1:

**Comment by ShutUpPvP** [comment]
Hope this mfker that copies the bot will get fked up :P 
U updated the bot right when a dragoran spawned 2km away... :( xD

**Comment by DR6116** [comment]
could someone add something that will put eggs in incubators? when i tried necroBot they had something that did that and it was very convenient.

**Comment by BerkanYildiz** [comment]
The owner of the site is also the lwner of VIP SPUC3NGINE

**Comment by BerkanYildiz** [comment]
I just sent a DMCA Report, and contacted them.

**Pull request closed without merging**
