### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by HaydarOzturk**
I change the neccasry files for GUI translation

### CODE REVIEW

**Comment by IceQ1337** [comment]
You made mistakes in the Button_Click Events.
On a language button, enable all other language buttons and disable the one clicked.

**Comment by HaydarOzturk** [comment]
Can you point out the parts that I messed up?

**Comment by HaydarOzturk** [comment]
Oh I understand now. Thanks man. If I update my repository will it gonna be updated on pull request too or should I create a new one?

**Comment by IceQ1337** [comment]
Update your repository. Sync it with your fork. It will be updated on your current pull request.

**Comment by HaydarOzturk** [comment]
Thanks mate. I search it but I didn't see your contact info. How can I get in touch with you @IceQ1337

**Comment by IceQ1337** [comment]
Add me on Steam: steamcommunity.com/id/iceqderboss2

**Comment by Ar1i** [comment]
Putting that in, thanks!

**Comment by IceQ1337** [comment]
@Ar1i Denk daran, dass du jetzt den Conflict aber nicht vergisst nachdem du meine Spanisch-Extension geadded hat :*

**Comment by Ar1i** [comment]
Y sehe ich ja packe das per Hand rein

**Comment by HaydarOzturk** [comment]
You can delete now. I noticed my steam hasn't have the rights to add others :) Sorry for taking your time anyway.

**Comment by Ar1i** [comment]
Added, thanks!

**Pull request closed without merging**
