### PR TITLE
Added pokedesk number to pokemon list view

### PR DESCRIPTION
**Pull request by Xelwon**

### CODE REVIEW

**Comment by Logxn** [comment]
Please solve the conflicts :X

**Comment by Xelwon** [comment]
I can't see confilcts, my fork is from yesterday.

How can I see conflicts ?

How can I update my fork (https://github.com/Xelwon/PokemonGo-Bot) to latest version (https://github.com/Ar1i/PokemonGo-Bot)?

**Comment by Logxn** [comment]
If you are in the client, there must be a "Update from Ar1i master" button.

If you click that it will show your conflicts

**Comment by Ar1i** [comment]
alt is getting fixed at bot start, if its zero. so it's not needed to save altidude. Or change it! The IV Stats I will use, thanks for that.

**Comment by Xelwon** [comment]
Ok, thans ar1i. 
I'm getting crazy with github client desktop and solving confligts ( :O ). 
---- And conficts was only a beginupdate and a endupdate :D :D ---

Then , is not interesting  save altitude either?

 https://github.com/Ar1i/PokemonGo-Bot/pull/3630/commits/76eaa4c1fbc6cf622bbe7fd4ae923f8d4a6e4a18

**Comment by Ar1i** [comment]
no use for that, i dont know why it merged lul, reverting that back! but thanks for helping!

**Comment by Xelwon** [comment]
Ar1i, I needed change functions names, to all the logic use IV pefection instead of CP perfection.

Here is my last commit showing the differences in the two affected files.

https://github.com/Xelwon/PokemonGo-Bot/commit/c7c11735f9d4533d4f4f10ab15c652461e0af8c3

**Pull request merged**
