### PR TITLE
Wait until 60 pokemons to evolve and limited incubators use only 10 km eggs

### PR DESCRIPTION
**Pull request by FrancoRodrigues**
2 small features to the bot.

I didn't have enough time to understand the GUI and Config files. Im my next pull request I will put the variable MinPokemonToEvolve on the GUI with the code to save and read the config files

### CODE REVIEW

**Comment by Viper2k4** [comment]
OK and what is when there is no 10km egg? ^^

**Comment by FrancoRodrigues** [comment]
The bot will wait until a new 10km egg. This is the best usage for a limited incumbator.

**Comment by SscSPs** [comment]
and will it use unlimited one with 2km/5km?

**Comment by FrancoRodrigues** [comment]
No, there are 2 rules... 

1) unlimited incumbator will pickup the first egg ordering by size (picking up the smallers egg first). I didn't change that rule.

2) limited incumbator (on the original rule) pick up the biggest egg, but eventually will use that incumbator on a 2km egg. I change that rule to use only in 10 km eggs, this is the best use for that incumbator.
Ex: an incumbator hatch three eggs 2km, 5km and 10km (total 17km), now the same incumbator will hatch 3 eggs of 10km (total 30km).

PS: Sorry for my poor english.

**Pull request closed without merging**
