### PR TITLE
*Randomize Throws* / Verbose Items Listing / Toggle Loot / Improve Pokestop Camping

### PR DESCRIPTION
**Pull request by MTK4355**

### CODE REVIEW

**Comment by PrOCheaTer** [comment]
How i use the Bot:

- Using the same ID from Phone and Phonename.
- Speed is Random function between: 1-11 km/h all 1-46 Secounds my Speed go up or down..
- Walkradius is 1500m
- Bot starts automaticly at 9am the Bot stopps 90-240 Minutes later for 3 hours and some min. Then he go back Online...
- In Night the Bot is sleeping.
-Berry i use 25%
- Pokemonsettings: Evolve the good Pokemons (google^^) and the bad pokemons i dont catch / double Pokemons: 4 / Max IV to send: 55% / max cp to send 650 / Items = maxium 275... / use Proxy? No :dancer: 


this is how i use the Bot and its fucking undetected <3

I hope i can help you guys a bit ;)

sorry for my bad english :D im from russia and living in germany :D

**Comment by MTK4355** [comment]
@Ar1i 
This might be my last big pull for a while... I have to go make some money now.... lol.

**Comment by Ar1i** [comment]
lul thanks for your awesome work!

**Comment by Monadologie** [comment]
@Ar1i Can you please, make a build for the latest version?

**Comment by Hydro420** [comment]
@Monadologie In due time my friend.

**Comment by Hydro420** [comment]
@PrOCheaTer What device are you running? I dont see any option for iPhones?

How did you set up the bot to run/sleep automatically? PM me if you can please?

**Pull request merged**
