### PR TITLE
Italian & Romanian Translation

### PR DESCRIPTION
**Pull request by IceQ1337**

### CODE REVIEW

**Comment by AcolyteIT** [comment]
Attento che alcune cose non le hai tradotte ed altre sono tradotte in dialetto come "dicci"

**Comment by AcolyteIT** [comment]
[italian.txt](https://github.com/Ar1i/PokemonGo-Bot/files/397717/italian.txt)

**Comment by AcolyteIT** [comment]
prova a fare un misto, se non vuoi grazie lo stesso per la traduzione

**Comment by AcolyteIT** [comment]
Not to be arrogant but this translation isn't that good

**Comment by IceQ1337** [comment]
@AcolyteIT I don't speak any italian so I can't know^^

**Comment by AcolyteIT** [comment]
I submitted a new one, I don't want to take the guy place but it's better xd

**Comment by AcolyteIT** [comment]
The romanian one isn't that nice, I only have romanian parents. but at least it's something.

**Comment by IceQ1337** [comment]
Added your Italian Translation

**Comment by IceQ1337** [comment]
@Ar1i jetzt wo du deinen Fix schon gemerged hast, baust du den PR hier selbst eben ein?

**Comment by IceQ1337** [comment]
Vorsicht. Das hat zwar hier keine Conflicts mehr, aber nur weil ich eben dein Update reingemerged hab.
Hoffe der Rest vom Inhalt hier stimmt dann noch.

**Comment by daniele978** [comment]
[File italian.zip](https://github.com/Ar1i/PokemonGo-Bot/files/398058/File.italian.zip)
Hello my name is daniele978, i'm italian boy, i modified the files for Italian

**Comment by AcolyteIT** [comment]
daniele you copied them from the spanish one... I checked them right now

**Comment by IceQ1337** [comment]
@daniele978 There are already italian translations. Sorry dude.

**Comment by AcolyteIT** [comment]
A friend is remaking the romanian translation, how can i update the old one?

**Comment by IceQ1337** [comment]
Put it in here. They are still not in the main repository because i am currently not able to upload a request for that. @Ar1i will do that by himself when he got time for that. Just put a pastebin here :D

**Comment by AcolyteIT** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1028 here is the link, I want him to take his credits :P

**Comment by IceQ1337** [comment]
@Ar1i will take a look at this then. Thank you!

**Comment by gRullo** [comment]
First of all, thanks for your AWESOME job, this is the best Pgo bot out there hands down ! Constantly improved and upgraded for even better. 

So, I really would like to enjoy the italian translation if its still in your plans. 
Thanks in advance ! :)

**Comment by AcolyteIT** [comment]
@gRullo  I think you just need for the next update, they already got the italian translation, only need to add it.

**Comment by IceQ1337** [comment]
#Closed because of branch conflicts.
Check the italian and romanian translation here to edit: #1224
It will get implemented if there is enough time for it.

**Pull request closed without merging**
